# Generated by Django 5.1 on 2024-09-12 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.DeleteModel(
            name='Lecturer',
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.TextField(default=None),
        ),
    ]
