# Generated by Django 5.1 on 2024-09-22 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_authors_alter_book_publisher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
    ]
