# Generated by Django 5.1 on 2024-09-26 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
    ]
